// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pb/protos/events.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

extension Anytype_Event.Key {
    public struct Update: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      public var spaceKeyID: String = String()

      public var encryptionKeyID: String = String()

      public var encryptionKey: String = String()

      public var unknownFields = SwiftProtobuf.UnknownStorage()

      public init() {}
    }    
}

extension Anytype_Event.Key.Update: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anytype_Event.Key.protoMessageName + ".Update"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "spaceKeyId"),
    2: .same(proto: "encryptionKeyId"),
    3: .same(proto: "encryptionKey"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.spaceKeyID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.encryptionKeyID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.encryptionKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.spaceKeyID.isEmpty {
      try visitor.visitSingularStringField(value: self.spaceKeyID, fieldNumber: 1)
    }
    if !self.encryptionKeyID.isEmpty {
      try visitor.visitSingularStringField(value: self.encryptionKeyID, fieldNumber: 2)
    }
    if !self.encryptionKey.isEmpty {
      try visitor.visitSingularStringField(value: self.encryptionKey, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anytype_Event.Key.Update, rhs: Anytype_Event.Key.Update) -> Bool {
    if lhs.spaceKeyID != rhs.spaceKeyID {return false}
    if lhs.encryptionKeyID != rhs.encryptionKeyID {return false}
    if lhs.encryptionKey != rhs.encryptionKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anytype"
