append_commit_message: 
commit_message: '%language% [skip ci]'
files:
  - source: /Anytype/Resources/Strings/en.lproj/*
    translation: /Anytype/Resources/Strings/%osx_code%/%original_file_name%
  - source: /Modules/Loc/Sources/Loc/Resources/*.xcstrings
    translation: /Modules/Loc/Sources/Loc/Resources/%original_file_name%
    multilingual: 1
  - source: /Modules/ProtobufMessages/Sources/Loc/Resources/LocalizableError.xcstrings
    translation: /Modules/ProtobufMessages/Sources/Loc/Resources/LocalizableError.xcstrings
    multilingual: 1
