public enum DetailsKind: String {
    case id = "id"
    case name = "name"
    case iconEmoji = "iconEmoji"
    case iconImage = "iconImage"
    case coverId = "coverId"
    case coverType = "coverType"
    case isArchived = "isArchived"
    case isFavorite = "isFavorite"
    case description = "description"
    case layout = "layout"
    case layoutAlign = "layoutAlign"
    case done = "done"
    case isHidden = "isHidden"
    case lastOpenedDate = "lastOpenedDate"
    case type = "type"    
    case lastModifiedDate = "lastModifiedDate"
    case lastModifiedBy = "lastModifiedBy"
    case creator = "creator"
    case createdDate = "createdDate"
    case featuredRelations = "featuredRelations"
}
