enum CustomIcon: String, CaseIterable {
    case accessibility
    case addCircle
    case airplane
    case alarm
    case albums
    case alertCircle
    case americanFootball
    case analytics
    case aperture
    case apps
    case archive
    case arrowBackCircle
    case arrowDownCircle
    case arrowForwardCircle
    case arrowRedo
    case arrowRedoCircle
    case arrowUndo
    case arrowUndoCircle
    case arrowUpCircle
    case atCircle
    case attach
    case backspace
    case bag
    case bagAdd
    case bagCheck
    case bagHandle
    case bagRemove
    case balloon
    case ban
    case bandage
    case barChart
    case barbell
    case barcode
    case baseball
    case basket
    case basketball
    case batteryCharging
    case batteryDead
    case batteryFull
    case batteryHalf
    case beaker
    case bed
    case beer
    case bicycle
    case binoculars
    case bluetooth
    case boat
    case body
    case bonfire
    case book
    case bookmark
    case bookmarks
    case bowlingBall
    case briefcase
    case browsers
    case brush
    case bug
    case build
    case bulb
    case bus
    case business
    case cafe
    case calculator
    case calendar
    case calendarClear
    case calendarNumber
    case call
    case camera
    case cameraReverse
    case car
    case carSport
    case card
    case caretBack
    case caretBackCircle
    case caretDown
    case caretDownCircle
    case caretForward
    case caretForwardCircle
    case caretUp
    case caretUpCircle
    case cart
    case cash
    case cellular
    case chatbox
    case chatboxEllipses
    case chatbubble
    case chatbubbleEllipses
    case chatbubbles
    case checkbox
    case checkmarkCircle
    case checkmarkDoneCircle
    case chevronBackCircle
    case chevronDownCircle
    case chevronForwardCircle
    case chevronUpCircle
    case clipboard
    case closeCircle
    case cloud
    case cloudCircle
    case cloudDone
    case cloudDownload
    case cloudOffline
    case cloudUpload
    case cloudy
    case cloudyNight
    case code
    case codeSlash
    case cog
    case colorFill
    case colorFilter
    case colorPalette
    case colorWand
    case compass
    case construct
    case contract
    case contrast
    case copy
    case create
    case crop
    case cube
    case cut
    case desktop
    case diamond
    case dice
    case disc
    case document
    case documentAttach
    case documentLock
    case documentText
    case documents
    case download
    case duplicate
    case ear
    case earth
    case easel
    case egg
    case ellipse
    case ellipsisHorizontalCircle
    case ellipsisVerticalCircle
    case enter
    case exit
    case expand
    case extensionPuzzle
    case eye
    case eyeOff
    case eyedrop
    case fastFood
    case female
    case fileTray
    case fileTrayFull
    case fileTrayStacked
    case film
    case filterCircle
    case fingerPrint
    case fish
    case fitness
    case flag
    case flame
    case flash
    case flashOff
    case flashlight
    case flask
    case flower
    case folder
    case folderOpen
    case football
    case footsteps
    case funnel
    case gameController
    case gift
    case gitBranch
    case gitCommit
    case gitCompare
    case gitMerge
    case gitNetwork
    case gitPullRequest
    case glasses
    case globe
    case golf
    case grid
    case hammer
    case handLeft
    case handRight
    case happy
    case hardwareChip
    case headset
    case heart
    case heartCircle
    case heartDislike
    case heartDislikeCircle
    case heartHalf
    case helpBuoy
    case helpCircle
    case home
    case hourglass
    case iceCream
    case idCard
    case image
    case images
    case infinite
    case informationCircle
    case invertMode
    case journal
    case key
    case keypad
    case language
    case laptop
    case layers
    case leaf
    case library
    case link
    case list
    case listCircle
    case locate
    case location
    case lockClosed
    case lockOpen
    case logIn
    case logOut
    case logoAlipay
    case logoAmazon
    case logoAmplify
    case logoAndroid
    case magnet
    case mail
    case mailOpen
    case mailUnread
    case male
    case maleFemale
    case man
    case map
    case medal
    case medical
    case medkit
    case megaphone
    case menu
    case mic
    case micCircle
    case micOff
    case micOffCircle
    case moon
    case move
    case musicalNote
    case musicalNotes
    case navigate
    case navigateCircle
    case newspaper
    case notifications
    case notificationsCircle
    case notificationsOff
    case notificationsOffCircle
    case nuclear
    case nutrition
    case options
    case paperPlane
    case partlySunny
    case pause
    case pauseCircle
    case paw
    case pencil
    case people
    case peopleCircle
    case person
    case personAdd
    case personCircle
    case personRemove
    case phoneLandscape
    case phonePortrait
    case pieChart
    case pin
    case pint
    case pizza
    case planet
    case play
    case playBack
    case playBackCircle
    case playCircle
    case playForward
    case playForwardCircle
    case playSkipBack
    case playSkipBackCircle
    case playSkipForward
    case playSkipForwardCircle
    case podium
    case power
    case pricetag
    case pricetags
    case print
    case prism
    case pulse
    case push
    case qrCode
    case radio
    case radioButtonOff
    case radioButtonOn
    case rainy
    case reader
    case receipt
    case recording
    case refresh
    case refreshCircle
    case reload
    case reloadCircle
    case removeCircle
    case `repeat`
    case resize
    case restaurant
    case ribbon
    case rocket
    case rose
    case sad
    case save
    case scale
    case scan
    case scanCircle
    case school
    case search
    case searchCircle
    case send
    case server
    case settings
    case shapes
    case share
    case shareSocial
    case shield
    case shieldCheckmark
    case shieldHalf
    case shirt
    case shuffle
    case skull
    case snow
    case sparkles
    case speedometer
    case square
    case star
    case starHalf
    case statsChart
    case stop
    case stopCircle
    case stopwatch
    case storefront
    case subway
    case sunny
    case swapHorizontal
    case swapVertical
    case sync
    case syncCircle
    case tabletLandscape
    case tabletPortrait
    case telescope
    case tennisball
    case terminal
    case text
    case thermometer
    case thumbsDown
    case thumbsUp
    case thunderstorm
    case ticket
    case time
    case timer
    case today
    case toggle
    case trailSign
    case train
    case transgender
    case trash
    case trashBin
    case trendingDown
    case trendingUp
    case triangle
    case trophy
    case tv
    case umbrella
    case unlink
    case videocam
    case videocamOff
    case volumeHigh
    case volumeLow
    case volumeMedium
    case volumeMute
    case volumeOff
    case walk
    case wallet
    case warning
    case watch
    case water
    case wifi
    case wine
    case woman
    
    var imageAsset: ImageAsset {
        switch self {
        case .accessibility:
            return ImageAsset.CustomIcons.accessibility
        case .addCircle:
            return ImageAsset.CustomIcons.addCircle
        case .airplane:
            return ImageAsset.CustomIcons.airplane
        case .alarm:
            return ImageAsset.CustomIcons.alarm
        case .albums:
            return ImageAsset.CustomIcons.albums
        case .alertCircle:
            return ImageAsset.CustomIcons.alertCircle
        case .americanFootball:
            return ImageAsset.CustomIcons.americanFootball
        case .analytics:
            return ImageAsset.CustomIcons.analytics
        case .aperture:
            return ImageAsset.CustomIcons.aperture
        case .apps:
            return ImageAsset.CustomIcons.apps
        case .archive:
            return ImageAsset.CustomIcons.archive
        case .arrowBackCircle:
            return ImageAsset.CustomIcons.arrowBackCircle
        case .arrowDownCircle:
            return ImageAsset.CustomIcons.arrowDownCircle
        case .arrowForwardCircle:
            return ImageAsset.CustomIcons.arrowForwardCircle
        case .arrowRedo:
            return ImageAsset.CustomIcons.arrowRedo
        case .arrowRedoCircle:
            return ImageAsset.CustomIcons.arrowRedoCircle
        case .arrowUndo:
            return ImageAsset.CustomIcons.arrowUndo
        case .arrowUndoCircle:
            return ImageAsset.CustomIcons.arrowUndoCircle
        case .arrowUpCircle:
            return ImageAsset.CustomIcons.arrowUpCircle
        case .atCircle:
            return ImageAsset.CustomIcons.atCircle
        case .attach:
            return ImageAsset.CustomIcons.attach
        case .backspace:
            return ImageAsset.CustomIcons.backspace
        case .bag:
            return ImageAsset.CustomIcons.bag
        case .bagAdd:
            return ImageAsset.CustomIcons.bagAdd
        case .bagCheck:
            return ImageAsset.CustomIcons.bagCheck
        case .bagHandle:
            return ImageAsset.CustomIcons.bagHandle
        case .bagRemove:
            return ImageAsset.CustomIcons.bagRemove
        case .balloon:
            return ImageAsset.CustomIcons.balloon
        case .ban:
            return ImageAsset.CustomIcons.ban
        case .bandage:
            return ImageAsset.CustomIcons.bandage
        case .barChart:
            return ImageAsset.CustomIcons.barChart
        case .barbell:
            return ImageAsset.CustomIcons.barbell
        case .barcode:
            return ImageAsset.CustomIcons.barcode
        case .baseball:
            return ImageAsset.CustomIcons.baseball
        case .basket:
            return ImageAsset.CustomIcons.basket
        case .basketball:
            return ImageAsset.CustomIcons.basketball
        case .batteryCharging:
            return ImageAsset.CustomIcons.batteryCharging
        case .batteryDead:
            return ImageAsset.CustomIcons.batteryDead
        case .batteryFull:
            return ImageAsset.CustomIcons.batteryFull
        case .batteryHalf:
            return ImageAsset.CustomIcons.batteryHalf
        case .beaker:
            return ImageAsset.CustomIcons.beaker
        case .bed:
            return ImageAsset.CustomIcons.bed
        case .beer:
            return ImageAsset.CustomIcons.beer
        case .bicycle:
            return ImageAsset.CustomIcons.bicycle
        case .binoculars:
            return ImageAsset.CustomIcons.binoculars
        case .bluetooth:
            return ImageAsset.CustomIcons.bluetooth
        case .boat:
            return ImageAsset.CustomIcons.boat
        case .body:
            return ImageAsset.CustomIcons.body
        case .bonfire:
            return ImageAsset.CustomIcons.bonfire
        case .book:
            return ImageAsset.CustomIcons.book
        case .bookmark:
            return ImageAsset.CustomIcons.bookmark
        case .bookmarks:
            return ImageAsset.CustomIcons.bookmarks
        case .bowlingBall:
            return ImageAsset.CustomIcons.bowlingBall
        case .briefcase:
            return ImageAsset.CustomIcons.briefcase
        case .browsers:
            return ImageAsset.CustomIcons.browsers
        case .brush:
            return ImageAsset.CustomIcons.brush
        case .bug:
            return ImageAsset.CustomIcons.bug
        case .build:
            return ImageAsset.CustomIcons.build
        case .bulb:
            return ImageAsset.CustomIcons.bulb
        case .bus:
            return ImageAsset.CustomIcons.bus
        case .business:
            return ImageAsset.CustomIcons.business
        case .cafe:
            return ImageAsset.CustomIcons.cafe
        case .calculator:
            return ImageAsset.CustomIcons.calculator
        case .calendar:
            return ImageAsset.CustomIcons.calendar
        case .calendarClear:
            return ImageAsset.CustomIcons.calendarClear
        case .calendarNumber:
            return ImageAsset.CustomIcons.calendarNumber
        case .call:
            return ImageAsset.CustomIcons.call
        case .camera:
            return ImageAsset.CustomIcons.camera
        case .cameraReverse:
            return ImageAsset.CustomIcons.cameraReverse
        case .car:
            return ImageAsset.CustomIcons.car
        case .carSport:
            return ImageAsset.CustomIcons.carSport
        case .card:
            return ImageAsset.CustomIcons.card
        case .caretBack:
            return ImageAsset.CustomIcons.caretBack
        case .caretBackCircle:
            return ImageAsset.CustomIcons.caretBackCircle
        case .caretDown:
            return ImageAsset.CustomIcons.caretDown
        case .caretDownCircle:
            return ImageAsset.CustomIcons.caretDownCircle
        case .caretForward:
            return ImageAsset.CustomIcons.caretForward
        case .caretForwardCircle:
            return ImageAsset.CustomIcons.caretForwardCircle
        case .caretUp:
            return ImageAsset.CustomIcons.caretUp
        case .caretUpCircle:
            return ImageAsset.CustomIcons.caretUpCircle
        case .cart:
            return ImageAsset.CustomIcons.cart
        case .cash:
            return ImageAsset.CustomIcons.cash
        case .cellular:
            return ImageAsset.CustomIcons.cellular
        case .chatbox:
            return ImageAsset.CustomIcons.chatbox
        case .chatboxEllipses:
            return ImageAsset.CustomIcons.chatboxEllipses
        case .chatbubble:
            return ImageAsset.CustomIcons.chatbubble
        case .chatbubbleEllipses:
            return ImageAsset.CustomIcons.chatbubbleEllipses
        case .chatbubbles:
            return ImageAsset.CustomIcons.chatbubbles
        case .checkbox:
            return ImageAsset.CustomIcons.checkbox
        case .checkmarkCircle:
            return ImageAsset.CustomIcons.checkmarkCircle
        case .checkmarkDoneCircle:
            return ImageAsset.CustomIcons.checkmarkDoneCircle
        case .chevronBackCircle:
            return ImageAsset.CustomIcons.chevronBackCircle
        case .chevronDownCircle:
            return ImageAsset.CustomIcons.chevronDownCircle
        case .chevronForwardCircle:
            return ImageAsset.CustomIcons.chevronForwardCircle
        case .chevronUpCircle:
            return ImageAsset.CustomIcons.chevronUpCircle
        case .clipboard:
            return ImageAsset.CustomIcons.clipboard
        case .closeCircle:
            return ImageAsset.CustomIcons.closeCircle
        case .cloud:
            return ImageAsset.CustomIcons.cloud
        case .cloudCircle:
            return ImageAsset.CustomIcons.cloudCircle
        case .cloudDone:
            return ImageAsset.CustomIcons.cloudDone
        case .cloudDownload:
            return ImageAsset.CustomIcons.cloudDownload
        case .cloudOffline:
            return ImageAsset.CustomIcons.cloudOffline
        case .cloudUpload:
            return ImageAsset.CustomIcons.cloudUpload
        case .cloudy:
            return ImageAsset.CustomIcons.cloudy
        case .cloudyNight:
            return ImageAsset.CustomIcons.cloudyNight
        case .code:
            return ImageAsset.CustomIcons.code
        case .codeSlash:
            return ImageAsset.CustomIcons.codeSlash
        case .cog:
            return ImageAsset.CustomIcons.cog
        case .colorFill:
            return ImageAsset.CustomIcons.colorFill
        case .colorFilter:
            return ImageAsset.CustomIcons.colorFilter
        case .colorPalette:
            return ImageAsset.CustomIcons.colorPalette
        case .colorWand:
            return ImageAsset.CustomIcons.colorWand
        case .compass:
            return ImageAsset.CustomIcons.compass
        case .construct:
            return ImageAsset.CustomIcons.construct
        case .contract:
            return ImageAsset.CustomIcons.contract
        case .contrast:
            return ImageAsset.CustomIcons.contrast
        case .copy:
            return ImageAsset.CustomIcons.copy
        case .create:
            return ImageAsset.CustomIcons.create
        case .crop:
            return ImageAsset.CustomIcons.crop
        case .cube:
            return ImageAsset.CustomIcons.cube
        case .cut:
            return ImageAsset.CustomIcons.cut
        case .desktop:
            return ImageAsset.CustomIcons.desktop
        case .diamond:
            return ImageAsset.CustomIcons.diamond
        case .dice:
            return ImageAsset.CustomIcons.dice
        case .disc:
            return ImageAsset.CustomIcons.disc
        case .document:
            return ImageAsset.CustomIcons.document
        case .documentAttach:
            return ImageAsset.CustomIcons.documentAttach
        case .documentLock:
            return ImageAsset.CustomIcons.documentLock
        case .documentText:
            return ImageAsset.CustomIcons.documentText
        case .documents:
            return ImageAsset.CustomIcons.documents
        case .download:
            return ImageAsset.CustomIcons.download
        case .duplicate:
            return ImageAsset.CustomIcons.duplicate
        case .ear:
            return ImageAsset.CustomIcons.ear
        case .earth:
            return ImageAsset.CustomIcons.earth
        case .easel:
            return ImageAsset.CustomIcons.easel
        case .egg:
            return ImageAsset.CustomIcons.egg
        case .ellipse:
            return ImageAsset.CustomIcons.ellipse
        case .ellipsisHorizontalCircle:
            return ImageAsset.CustomIcons.ellipsisHorizontalCircle
        case .ellipsisVerticalCircle:
            return ImageAsset.CustomIcons.ellipsisVerticalCircle
        case .enter:
            return ImageAsset.CustomIcons.enter
        case .exit:
            return ImageAsset.CustomIcons.exit
        case .expand:
            return ImageAsset.CustomIcons.expand
        case .extensionPuzzle:
            return ImageAsset.CustomIcons.extensionPuzzle
        case .eye:
            return ImageAsset.CustomIcons.eye
        case .eyeOff:
            return ImageAsset.CustomIcons.eyeOff
        case .eyedrop:
            return ImageAsset.CustomIcons.eyedrop
        case .fastFood:
            return ImageAsset.CustomIcons.fastFood
        case .female:
            return ImageAsset.CustomIcons.female
        case .fileTray:
            return ImageAsset.CustomIcons.fileTray
        case .fileTrayFull:
            return ImageAsset.CustomIcons.fileTrayFull
        case .fileTrayStacked:
            return ImageAsset.CustomIcons.fileTrayStacked
        case .film:
            return ImageAsset.CustomIcons.film
        case .filterCircle:
            return ImageAsset.CustomIcons.filterCircle
        case .fingerPrint:
            return ImageAsset.CustomIcons.fingerPrint
        case .fish:
            return ImageAsset.CustomIcons.fish
        case .fitness:
            return ImageAsset.CustomIcons.fitness
        case .flag:
            return ImageAsset.CustomIcons.flag
        case .flame:
            return ImageAsset.CustomIcons.flame
        case .flash:
            return ImageAsset.CustomIcons.flash
        case .flashOff:
            return ImageAsset.CustomIcons.flashOff
        case .flashlight:
            return ImageAsset.CustomIcons.flashlight
        case .flask:
            return ImageAsset.CustomIcons.flask
        case .flower:
            return ImageAsset.CustomIcons.flower
        case .folder:
            return ImageAsset.CustomIcons.folder
        case .folderOpen:
            return ImageAsset.CustomIcons.folderOpen
        case .football:
            return ImageAsset.CustomIcons.football
        case .footsteps:
            return ImageAsset.CustomIcons.footsteps
        case .funnel:
            return ImageAsset.CustomIcons.funnel
        case .gameController:
            return ImageAsset.CustomIcons.gameController
        case .gift:
            return ImageAsset.CustomIcons.gift
        case .gitBranch:
            return ImageAsset.CustomIcons.gitBranch
        case .gitCommit:
            return ImageAsset.CustomIcons.gitCommit
        case .gitCompare:
            return ImageAsset.CustomIcons.gitCompare
        case .gitMerge:
            return ImageAsset.CustomIcons.gitMerge
        case .gitNetwork:
            return ImageAsset.CustomIcons.gitNetwork
        case .gitPullRequest:
            return ImageAsset.CustomIcons.gitPullRequest
        case .glasses:
            return ImageAsset.CustomIcons.glasses
        case .globe:
            return ImageAsset.CustomIcons.globe
        case .golf:
            return ImageAsset.CustomIcons.golf
        case .grid:
            return ImageAsset.CustomIcons.grid
        case .hammer:
            return ImageAsset.CustomIcons.hammer
        case .handLeft:
            return ImageAsset.CustomIcons.handLeft
        case .handRight:
            return ImageAsset.CustomIcons.handRight
        case .happy:
            return ImageAsset.CustomIcons.happy
        case .hardwareChip:
            return ImageAsset.CustomIcons.hardwareChip
        case .headset:
            return ImageAsset.CustomIcons.headset
        case .heart:
            return ImageAsset.CustomIcons.heart
        case .heartCircle:
            return ImageAsset.CustomIcons.heartCircle
        case .heartDislike:
            return ImageAsset.CustomIcons.heartDislike
        case .heartDislikeCircle:
            return ImageAsset.CustomIcons.heartDislikeCircle
        case .heartHalf:
            return ImageAsset.CustomIcons.heartHalf
        case .helpBuoy:
            return ImageAsset.CustomIcons.helpBuoy
        case .helpCircle:
            return ImageAsset.CustomIcons.helpCircle
        case .home:
            return ImageAsset.CustomIcons.home
        case .hourglass:
            return ImageAsset.CustomIcons.hourglass
        case .iceCream:
            return ImageAsset.CustomIcons.iceCream
        case .idCard:
            return ImageAsset.CustomIcons.idCard
        case .image:
            return ImageAsset.CustomIcons.image
        case .images:
            return ImageAsset.CustomIcons.images
        case .infinite:
            return ImageAsset.CustomIcons.infinite
        case .informationCircle:
            return ImageAsset.CustomIcons.informationCircle
        case .invertMode:
            return ImageAsset.CustomIcons.invertMode
        case .journal:
            return ImageAsset.CustomIcons.journal
        case .key:
            return ImageAsset.CustomIcons.key
        case .keypad:
            return ImageAsset.CustomIcons.keypad
        case .language:
            return ImageAsset.CustomIcons.language
        case .laptop:
            return ImageAsset.CustomIcons.laptop
        case .layers:
            return ImageAsset.CustomIcons.layers
        case .leaf:
            return ImageAsset.CustomIcons.leaf
        case .library:
            return ImageAsset.CustomIcons.library
        case .link:
            return ImageAsset.CustomIcons.link
        case .list:
            return ImageAsset.CustomIcons.list
        case .listCircle:
            return ImageAsset.CustomIcons.listCircle
        case .locate:
            return ImageAsset.CustomIcons.locate
        case .location:
            return ImageAsset.CustomIcons.location
        case .lockClosed:
            return ImageAsset.CustomIcons.lockClosed
        case .lockOpen:
            return ImageAsset.CustomIcons.lockOpen
        case .logIn:
            return ImageAsset.CustomIcons.logIn
        case .logOut:
            return ImageAsset.CustomIcons.logOut
        case .logoAlipay:
            return ImageAsset.CustomIcons.logoAlipay
        case .logoAmazon:
            return ImageAsset.CustomIcons.logoAmazon
        case .logoAmplify:
            return ImageAsset.CustomIcons.logoAmplify
        case .logoAndroid:
            return ImageAsset.CustomIcons.logoAndroid
        case .magnet:
            return ImageAsset.CustomIcons.magnet
        case .mail:
            return ImageAsset.CustomIcons.mail
        case .mailOpen:
            return ImageAsset.CustomIcons.mailOpen
        case .mailUnread:
            return ImageAsset.CustomIcons.mailUnread
        case .male:
            return ImageAsset.CustomIcons.male
        case .maleFemale:
            return ImageAsset.CustomIcons.maleFemale
        case .man:
            return ImageAsset.CustomIcons.man
        case .map:
            return ImageAsset.CustomIcons.map
        case .medal:
            return ImageAsset.CustomIcons.medal
        case .medical:
            return ImageAsset.CustomIcons.medical
        case .medkit:
            return ImageAsset.CustomIcons.medkit
        case .megaphone:
            return ImageAsset.CustomIcons.megaphone
        case .menu:
            return ImageAsset.CustomIcons.menu
        case .mic:
            return ImageAsset.CustomIcons.mic
        case .micCircle:
            return ImageAsset.CustomIcons.micCircle
        case .micOff:
            return ImageAsset.CustomIcons.micOff
        case .micOffCircle:
            return ImageAsset.CustomIcons.micOffCircle
        case .moon:
            return ImageAsset.CustomIcons.moon
        case .move:
            return ImageAsset.CustomIcons.move
        case .musicalNote:
            return ImageAsset.CustomIcons.musicalNote
        case .musicalNotes:
            return ImageAsset.CustomIcons.musicalNotes
        case .navigate:
            return ImageAsset.CustomIcons.navigate
        case .navigateCircle:
            return ImageAsset.CustomIcons.navigateCircle
        case .newspaper:
            return ImageAsset.CustomIcons.newspaper
        case .notifications:
            return ImageAsset.CustomIcons.notifications
        case .notificationsCircle:
            return ImageAsset.CustomIcons.notificationsCircle
        case .notificationsOff:
            return ImageAsset.CustomIcons.notificationsOff
        case .notificationsOffCircle:
            return ImageAsset.CustomIcons.notificationsOffCircle
        case .nuclear:
            return ImageAsset.CustomIcons.nuclear
        case .nutrition:
            return ImageAsset.CustomIcons.nutrition
        case .options:
            return ImageAsset.CustomIcons.options
        case .paperPlane:
            return ImageAsset.CustomIcons.paperPlane
        case .partlySunny:
            return ImageAsset.CustomIcons.partlySunny
        case .pause:
            return ImageAsset.CustomIcons.pause
        case .pauseCircle:
            return ImageAsset.CustomIcons.pauseCircle
        case .paw:
            return ImageAsset.CustomIcons.paw
        case .pencil:
            return ImageAsset.CustomIcons.pencil
        case .people:
            return ImageAsset.CustomIcons.people
        case .peopleCircle:
            return ImageAsset.CustomIcons.peopleCircle
        case .person:
            return ImageAsset.CustomIcons.person
        case .personAdd:
            return ImageAsset.CustomIcons.personAdd
        case .personCircle:
            return ImageAsset.CustomIcons.personCircle
        case .personRemove:
            return ImageAsset.CustomIcons.personRemove
        case .phoneLandscape:
            return ImageAsset.CustomIcons.phoneLandscape
        case .phonePortrait:
            return ImageAsset.CustomIcons.phonePortrait
        case .pieChart:
            return ImageAsset.CustomIcons.pieChart
        case .pin:
            return ImageAsset.CustomIcons.pin
        case .pint:
            return ImageAsset.CustomIcons.pint
        case .pizza:
            return ImageAsset.CustomIcons.pizza
        case .planet:
            return ImageAsset.CustomIcons.planet
        case .play:
            return ImageAsset.CustomIcons.play
        case .playBack:
            return ImageAsset.CustomIcons.playBack
        case .playBackCircle:
            return ImageAsset.CustomIcons.playBackCircle
        case .playCircle:
            return ImageAsset.CustomIcons.playCircle
        case .playForward:
            return ImageAsset.CustomIcons.playForward
        case .playForwardCircle:
            return ImageAsset.CustomIcons.playForwardCircle
        case .playSkipBack:
            return ImageAsset.CustomIcons.playSkipBack
        case .playSkipBackCircle:
            return ImageAsset.CustomIcons.playSkipBackCircle
        case .playSkipForward:
            return ImageAsset.CustomIcons.playSkipForward
        case .playSkipForwardCircle:
            return ImageAsset.CustomIcons.playSkipForwardCircle
        case .podium:
            return ImageAsset.CustomIcons.podium
        case .power:
            return ImageAsset.CustomIcons.power
        case .pricetag:
            return ImageAsset.CustomIcons.pricetag
        case .pricetags:
            return ImageAsset.CustomIcons.pricetags
        case .print:
            return ImageAsset.CustomIcons.print
        case .prism:
            return ImageAsset.CustomIcons.prism
        case .pulse:
            return ImageAsset.CustomIcons.pulse
        case .push:
            return ImageAsset.CustomIcons.push
        case .qrCode:
            return ImageAsset.CustomIcons.qrCode
        case .radio:
            return ImageAsset.CustomIcons.radio
        case .radioButtonOff:
            return ImageAsset.CustomIcons.radioButtonOff
        case .radioButtonOn:
            return ImageAsset.CustomIcons.radioButtonOn
        case .rainy:
            return ImageAsset.CustomIcons.rainy
        case .reader:
            return ImageAsset.CustomIcons.reader
        case .receipt:
            return ImageAsset.CustomIcons.receipt
        case .recording:
            return ImageAsset.CustomIcons.recording
        case .refresh:
            return ImageAsset.CustomIcons.refresh
        case .refreshCircle:
            return ImageAsset.CustomIcons.refreshCircle
        case .reload:
            return ImageAsset.CustomIcons.reload
        case .reloadCircle:
            return ImageAsset.CustomIcons.reloadCircle
        case .removeCircle:
            return ImageAsset.CustomIcons.removeCircle
        case .`repeat`:
            return ImageAsset.CustomIcons.repeat
        case .resize:
            return ImageAsset.CustomIcons.resize
        case .restaurant:
            return ImageAsset.CustomIcons.restaurant
        case .ribbon:
            return ImageAsset.CustomIcons.ribbon
        case .rocket:
            return ImageAsset.CustomIcons.rocket
        case .rose:
            return ImageAsset.CustomIcons.rose
        case .sad:
            return ImageAsset.CustomIcons.sad
        case .save:
            return ImageAsset.CustomIcons.save
        case .scale:
            return ImageAsset.CustomIcons.scale
        case .scan:
            return ImageAsset.CustomIcons.scan
        case .scanCircle:
            return ImageAsset.CustomIcons.scanCircle
        case .school:
            return ImageAsset.CustomIcons.school
        case .search:
            return ImageAsset.CustomIcons.search
        case .searchCircle:
            return ImageAsset.CustomIcons.searchCircle
        case .send:
            return ImageAsset.CustomIcons.send
        case .server:
            return ImageAsset.CustomIcons.server
        case .settings:
            return ImageAsset.CustomIcons.settings
        case .shapes:
            return ImageAsset.CustomIcons.shapes
        case .share:
            return ImageAsset.CustomIcons.share
        case .shareSocial:
            return ImageAsset.CustomIcons.shareSocial
        case .shield:
            return ImageAsset.CustomIcons.shield
        case .shieldCheckmark:
            return ImageAsset.CustomIcons.shieldCheckmark
        case .shieldHalf:
            return ImageAsset.CustomIcons.shieldHalf
        case .shirt:
            return ImageAsset.CustomIcons.shirt
        case .shuffle:
            return ImageAsset.CustomIcons.shuffle
        case .skull:
            return ImageAsset.CustomIcons.skull
        case .snow:
            return ImageAsset.CustomIcons.snow
        case .sparkles:
            return ImageAsset.CustomIcons.sparkles
        case .speedometer:
            return ImageAsset.CustomIcons.speedometer
        case .square:
            return ImageAsset.CustomIcons.square
        case .star:
            return ImageAsset.CustomIcons.star
        case .starHalf:
            return ImageAsset.CustomIcons.starHalf
        case .statsChart:
            return ImageAsset.CustomIcons.statsChart
        case .stop:
            return ImageAsset.CustomIcons.stop
        case .stopCircle:
            return ImageAsset.CustomIcons.stopCircle
        case .stopwatch:
            return ImageAsset.CustomIcons.stopwatch
        case .storefront:
            return ImageAsset.CustomIcons.storefront
        case .subway:
            return ImageAsset.CustomIcons.subway
        case .sunny:
            return ImageAsset.CustomIcons.sunny
        case .swapHorizontal:
            return ImageAsset.CustomIcons.swapHorizontal
        case .swapVertical:
            return ImageAsset.CustomIcons.swapVertical
        case .sync:
            return ImageAsset.CustomIcons.sync
        case .syncCircle:
            return ImageAsset.CustomIcons.syncCircle
        case .tabletLandscape:
            return ImageAsset.CustomIcons.tabletLandscape
        case .tabletPortrait:
            return ImageAsset.CustomIcons.tabletPortrait
        case .telescope:
            return ImageAsset.CustomIcons.telescope
        case .tennisball:
            return ImageAsset.CustomIcons.tennisball
        case .terminal:
            return ImageAsset.CustomIcons.terminal
        case .text:
            return ImageAsset.CustomIcons.text
        case .thermometer:
            return ImageAsset.CustomIcons.thermometer
        case .thumbsDown:
            return ImageAsset.CustomIcons.thumbsDown
        case .thumbsUp:
            return ImageAsset.CustomIcons.thumbsUp
        case .thunderstorm:
            return ImageAsset.CustomIcons.thunderstorm
        case .ticket:
            return ImageAsset.CustomIcons.ticket
        case .time:
            return ImageAsset.CustomIcons.time
        case .timer:
            return ImageAsset.CustomIcons.timer
        case .today:
            return ImageAsset.CustomIcons.today
        case .toggle:
            return ImageAsset.CustomIcons.toggle
        case .trailSign:
            return ImageAsset.CustomIcons.trailSign
        case .train:
            return ImageAsset.CustomIcons.train
        case .transgender:
            return ImageAsset.CustomIcons.transgender
        case .trash:
            return ImageAsset.CustomIcons.trash
        case .trashBin:
            return ImageAsset.CustomIcons.trashBin
        case .trendingDown:
            return ImageAsset.CustomIcons.trendingDown
        case .trendingUp:
            return ImageAsset.CustomIcons.trendingUp
        case .triangle:
            return ImageAsset.CustomIcons.triangle
        case .trophy:
            return ImageAsset.CustomIcons.trophy
        case .tv:
            return ImageAsset.CustomIcons.tv
        case .umbrella:
            return ImageAsset.CustomIcons.umbrella
        case .unlink:
            return ImageAsset.CustomIcons.unlink
        case .videocam:
            return ImageAsset.CustomIcons.videocam
        case .videocamOff:
            return ImageAsset.CustomIcons.videocamOff
        case .volumeHigh:
            return ImageAsset.CustomIcons.volumeHigh
        case .volumeLow:
            return ImageAsset.CustomIcons.volumeLow
        case .volumeMedium:
            return ImageAsset.CustomIcons.volumeMedium
        case .volumeMute:
            return ImageAsset.CustomIcons.volumeMute
        case .volumeOff:
            return ImageAsset.CustomIcons.volumeOff
        case .walk:
            return ImageAsset.CustomIcons.walk
        case .wallet:
            return ImageAsset.CustomIcons.wallet
        case .warning:
            return ImageAsset.CustomIcons.warning
        case .watch:
            return ImageAsset.CustomIcons.watch
        case .water:
            return ImageAsset.CustomIcons.water
        case .wifi:
            return ImageAsset.CustomIcons.wifi
        case .wine:
            return ImageAsset.CustomIcons.wine
        case .woman:
            return ImageAsset.CustomIcons.woman
        }
    }
}
