// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pkg/lib/pb/model/protos/models.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf
extension Anytype_Model_Restrictions {

  public enum DataviewRestriction: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case dvnone // = 0
    case dvrelation // = 1
    case dvcreateObject // = 2
    case dvviews // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .dvnone
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0:
          self = .dvnone
      case 1:
          self = .dvrelation
      case 2:
          self = .dvcreateObject
      case 3:
          self = .dvviews
      default:
          self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .dvnone:
          return 0
      case .dvrelation:
          return 1
      case .dvcreateObject:
          return 2
      case .dvviews:
          return 3
      case .UNRECOGNIZED(let i):
          return i
      }
    }

  }
}

extension Anytype_Model_Restrictions.DataviewRestriction: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Anytype_Model_Restrictions.DataviewRestriction] = [
    .dvnone,
    .dvrelation,
    .dvcreateObject,
    .dvviews,
  ]
}
extension Anytype_Model_Restrictions.DataviewRestriction: @unchecked Sendable {
}

extension Anytype_Model_Restrictions.DataviewRestriction: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "DVNone"),
    1: .same(proto: "DVRelation"),
    2: .same(proto: "DVCreateObject"),
    3: .same(proto: "DVViews"),
  ]
}

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {
  }
  typealias Version = _2
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anytype.model"
