// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pkg/lib/pb/model/protos/models.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf
extension Anytype_Model_Block {

  public enum Position: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case none // = 0

    /// above target block
    case top // = 1

    /// under target block
    case bottom // = 2

    /// to left of target block
    case left // = 3

    /// to right of target block
    case right // = 4

    /// inside target block, as last block
    case inner // = 5

    /// replace target block
    case replace // = 6

    /// inside target block, as first block
    case innerFirst // = 7
    case UNRECOGNIZED(Int)

    public init() {
      self = .none
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0:
          self = .none
      case 1:
          self = .top
      case 2:
          self = .bottom
      case 3:
          self = .left
      case 4:
          self = .right
      case 5:
          self = .inner
      case 6:
          self = .replace
      case 7:
          self = .innerFirst
      default:
          self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .none:
          return 0
      case .top:
          return 1
      case .bottom:
          return 2
      case .left:
          return 3
      case .right:
          return 4
      case .inner:
          return 5
      case .replace:
          return 6
      case .innerFirst:
          return 7
      case .UNRECOGNIZED(let i):
          return i
      }
    }

  }
}

extension Anytype_Model_Block.Position: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Anytype_Model_Block.Position] = [
    .none,
    .top,
    .bottom,
    .left,
    .right,
    .inner,
    .replace,
    .innerFirst,
  ]
}
extension Anytype_Model_Block.Position: @unchecked Sendable {
}

extension Anytype_Model_Block.Position: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "None"),
    1: .same(proto: "Top"),
    2: .same(proto: "Bottom"),
    3: .same(proto: "Left"),
    4: .same(proto: "Right"),
    5: .same(proto: "Inner"),
    6: .same(proto: "Replace"),
    7: .same(proto: "InnerFirst"),
  ]
}

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {
  }
  typealias Version = _2
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anytype.model"
