// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pkg/lib/pb/model/protos/models.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

extension Anytype_Model_Relation {

  public enum Scope: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int

    /// stored within the object
    case object // = 0

    /// stored within the object type
    case type // = 1

    /// aggregated from the dataview of sets of the same object type
    case setOfTheSameType // = 2

    /// aggregated from the dataview of sets of the same object type
    case objectsOfTheSameType // = 3

    /// aggregated from relations library
    case library // = 4
    case UNRECOGNIZED(Int)

    public init() {
      self = .object
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .object
      case 1: self = .type
      case 2: self = .setOfTheSameType
      case 3: self = .objectsOfTheSameType
      case 4: self = .library
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .object: return 0
      case .type: return 1
      case .setOfTheSameType: return 2
      case .objectsOfTheSameType: return 3
      case .library: return 4
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Anytype_Model_Relation.Scope] = [
      .object,
      .type,
      .setOfTheSameType,
      .objectsOfTheSameType,
      .library,
    ]

  }}

extension Anytype_Model_Relation.Scope: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "object"),
    1: .same(proto: "type"),
    2: .same(proto: "setOfTheSameType"),
    3: .same(proto: "objectsOfTheSameType"),
    4: .same(proto: "library"),
  ]
}

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anytype.model"
