// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pkg/lib/pb/model/protos/models.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

public enum Anytype_Model_SmartBlockType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// deprecated
  case accountOld // = 0
  case page // = 16
  case profilePage // = 17
  case home // = 32
  case archive // = 48
  case widget // = 112
  case file // = 256
  case template // = 288
  case bundledTemplate // = 289

  /// DEPRECATED
  case bundledRelation // = 512
  case subObject // = 513

  /// DEPRECATED
  case bundledObjectType // = 514
  case anytypeProfile // = 515
  case date // = 516
  case workspace // = 518
  case strelation // = 521
  case sttype // = 528
  case strelationOption // = 529
  case spaceView // = 530
  case identity // = 532
  case participant // = 534
  case missingObject // = 519
  case fileObject // = 533
  case notificationObject // = 535
  case devicesObject // = 536

  /// Container for any-store based chats
  case chatObject // = 537

  /// Any-store based object for chat
  case chatDerivedObject // = 544

  /// Container for account data in tech space
  case accountObject // = 545

  /// used to show virtual objects, like AI response generated on the fly
  case ephemeralVirtualObject // = 546
  case UNRECOGNIZED(Int)

  public init() {
    self = .accountOld
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .accountOld
    case 16: self = .page
    case 17: self = .profilePage
    case 32: self = .home
    case 48: self = .archive
    case 112: self = .widget
    case 256: self = .file
    case 288: self = .template
    case 289: self = .bundledTemplate
    case 512: self = .bundledRelation
    case 513: self = .subObject
    case 514: self = .bundledObjectType
    case 515: self = .anytypeProfile
    case 516: self = .date
    case 518: self = .workspace
    case 519: self = .missingObject
    case 521: self = .strelation
    case 528: self = .sttype
    case 529: self = .strelationOption
    case 530: self = .spaceView
    case 532: self = .identity
    case 533: self = .fileObject
    case 534: self = .participant
    case 535: self = .notificationObject
    case 536: self = .devicesObject
    case 537: self = .chatObject
    case 544: self = .chatDerivedObject
    case 545: self = .accountObject
    case 546: self = .ephemeralVirtualObject
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .accountOld: return 0
    case .page: return 16
    case .profilePage: return 17
    case .home: return 32
    case .archive: return 48
    case .widget: return 112
    case .file: return 256
    case .template: return 288
    case .bundledTemplate: return 289
    case .bundledRelation: return 512
    case .subObject: return 513
    case .bundledObjectType: return 514
    case .anytypeProfile: return 515
    case .date: return 516
    case .workspace: return 518
    case .missingObject: return 519
    case .strelation: return 521
    case .sttype: return 528
    case .strelationOption: return 529
    case .spaceView: return 530
    case .identity: return 532
    case .fileObject: return 533
    case .participant: return 534
    case .notificationObject: return 535
    case .devicesObject: return 536
    case .chatObject: return 537
    case .chatDerivedObject: return 544
    case .accountObject: return 545
    case .ephemeralVirtualObject: return 546
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Anytype_Model_SmartBlockType] = [
    .accountOld,
    .page,
    .profilePage,
    .home,
    .archive,
    .widget,
    .file,
    .template,
    .bundledTemplate,
    .bundledRelation,
    .subObject,
    .bundledObjectType,
    .anytypeProfile,
    .date,
    .workspace,
    .strelation,
    .sttype,
    .strelationOption,
    .spaceView,
    .identity,
    .participant,
    .missingObject,
    .fileObject,
    .notificationObject,
    .devicesObject,
    .chatObject,
    .chatDerivedObject,
    .accountObject,
    .ephemeralVirtualObject,
  ]

}

extension Anytype_Model_SmartBlockType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "AccountOld"),
    16: .same(proto: "Page"),
    17: .same(proto: "ProfilePage"),
    32: .same(proto: "Home"),
    48: .same(proto: "Archive"),
    112: .same(proto: "Widget"),
    256: .same(proto: "File"),
    288: .same(proto: "Template"),
    289: .same(proto: "BundledTemplate"),
    512: .same(proto: "BundledRelation"),
    513: .same(proto: "SubObject"),
    514: .same(proto: "BundledObjectType"),
    515: .same(proto: "AnytypeProfile"),
    516: .same(proto: "Date"),
    518: .same(proto: "Workspace"),
    519: .same(proto: "MissingObject"),
    521: .same(proto: "STRelation"),
    528: .same(proto: "STType"),
    529: .same(proto: "STRelationOption"),
    530: .same(proto: "SpaceView"),
    532: .same(proto: "Identity"),
    533: .same(proto: "FileObject"),
    534: .same(proto: "Participant"),
    535: .same(proto: "NotificationObject"),
    536: .same(proto: "DevicesObject"),
    537: .same(proto: "ChatObject"),
    544: .same(proto: "ChatDerivedObject"),
    545: .same(proto: "AccountObject"),
    546: .same(proto: "EphemeralVirtualObject"),
  ]
}

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anytype.model"
