// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pkg/lib/pb/model/protos/models.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf
extension Anytype_Model_Metadata {

  public enum OneOf_Payload: Equatable {
    case identity(Anytype_Model_Metadata.Payload.IdentityPayload)

  #if !swift(>=4.1)
    public static func ==(lhs: Anytype_Model_Metadata.OneOf_Payload, rhs: Anytype_Model_Metadata.OneOf_Payload) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.identity, .identity):
          return {
                  guard case .identity(let l) = lhs, case .identity(let r) = rhs else {
                      preconditionFailure()
                  }
                  return l == r
                }()
      }
    }
  #endif
  }
}
extension Anytype_Model_Metadata.OneOf_Payload: @unchecked Sendable {
}

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {
  }
  typealias Version = _2
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anytype.model"
