// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pkg/lib/pb/model/protos/models.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf
public extension Anytype_Model_InternalFlag {

  /// Use such a weird construction due to the issue with imported repeated enum type
  /// Look https://github.com/golang/protobuf/issues/1135 for more information.
  public enum Value: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case editorDeleteEmpty // = 0
    case editorSelectType // = 1
    case editorSelectTemplate // = 2
    case collectionDontIndexLinks // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .editorDeleteEmpty
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0:
          self = .editorDeleteEmpty
      case 1:
          self = .editorSelectType
      case 2:
          self = .editorSelectTemplate
      case 3:
          self = .collectionDontIndexLinks
      default:
          self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .editorDeleteEmpty:
          return 0
      case .editorSelectType:
          return 1
      case .editorSelectTemplate:
          return 2
      case .collectionDontIndexLinks:
          return 3
      case .UNRECOGNIZED(let i):
          return i
      }
    }

  }
}

extension Anytype_Model_InternalFlag.Value: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Anytype_Model_InternalFlag.Value] = [
    .editorDeleteEmpty,
    .editorSelectType,
    .editorSelectTemplate,
    .collectionDontIndexLinks,
  ]
}
extension Anytype_Model_InternalFlag.Value: @unchecked Sendable {
}

extension Anytype_Model_InternalFlag.Value: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "editorDeleteEmpty"),
    1: .same(proto: "editorSelectType"),
    2: .same(proto: "editorSelectTemplate"),
    3: .same(proto: "collectionDontIndexLinks"),
  ]
}

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {
  }
  typealias Version = _2
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anytype.model"