// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pkg/lib/pb/model/protos/models.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

extension Anytype_Model_Block {

  public enum OneOf_Content: Equatable, Sendable {
    case smartblock(Anytype_Model_Block.Content.Smartblock)
    case text(Anytype_Model_Block.Content.Text)
    case file(Anytype_Model_Block.Content.File)
    case layout(Anytype_Model_Block.Content.Layout)
    case div(Anytype_Model_Block.Content.Div)
    case bookmark(Anytype_Model_Block.Content.Bookmark)
    case icon(Anytype_Model_Block.Content.Icon)
    case link(Anytype_Model_Block.Content.Link)
    case dataview(Anytype_Model_Block.Content.Dataview)
    case relation(Anytype_Model_Block.Content.Relation)
    case featuredRelations(Anytype_Model_Block.Content.FeaturedRelations)
    case latex(Anytype_Model_Block.Content.Latex)
    case tableOfContents(Anytype_Model_Block.Content.TableOfContents)
    case table(Anytype_Model_Block.Content.Table)
    case tableColumn(Anytype_Model_Block.Content.TableColumn)
    case tableRow(Anytype_Model_Block.Content.TableRow)
    case widget(Anytype_Model_Block.Content.Widget)
    case chat(Anytype_Model_Block.Content.Chat)

  }}

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anytype.model"
