// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: models.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

extension Anytype_Model_MembershipV2 {
    public struct Features: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var storageBytes: UInt64 = 0

    public var spaceReaders: UInt32 = 0

    public var spaceWriters: UInt32 = 0

    public var sharedSpaces: UInt32 = 0

    public var teamSeats: UInt32 = 0

    public var anyNameCount: UInt32 = 0

    public var anyNameMinLen: UInt32 = 0

    public var privateSpaces: UInt32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }    
}

extension Anytype_Model_MembershipV2.Features: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Anytype_Model_MembershipV2.protoMessageName + ".Features"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}storageBytes\0\u{1}spaceReaders\0\u{1}spaceWriters\0\u{1}sharedSpaces\0\u{1}teamSeats\0\u{1}anyNameCount\0\u{1}anyNameMinLen\0\u{1}privateSpaces\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.storageBytes) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.spaceReaders) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.spaceWriters) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.sharedSpaces) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.teamSeats) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.anyNameCount) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.anyNameMinLen) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.privateSpaces) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.storageBytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.storageBytes, fieldNumber: 1)
    }
    if self.spaceReaders != 0 {
      try visitor.visitSingularUInt32Field(value: self.spaceReaders, fieldNumber: 2)
    }
    if self.spaceWriters != 0 {
      try visitor.visitSingularUInt32Field(value: self.spaceWriters, fieldNumber: 3)
    }
    if self.sharedSpaces != 0 {
      try visitor.visitSingularUInt32Field(value: self.sharedSpaces, fieldNumber: 4)
    }
    if self.teamSeats != 0 {
      try visitor.visitSingularUInt32Field(value: self.teamSeats, fieldNumber: 5)
    }
    if self.anyNameCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.anyNameCount, fieldNumber: 6)
    }
    if self.anyNameMinLen != 0 {
      try visitor.visitSingularUInt32Field(value: self.anyNameMinLen, fieldNumber: 7)
    }
    if self.privateSpaces != 0 {
      try visitor.visitSingularUInt32Field(value: self.privateSpaces, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Anytype_Model_MembershipV2.Features, rhs: Anytype_Model_MembershipV2.Features) -> Bool {
    if lhs.storageBytes != rhs.storageBytes {return false}
    if lhs.spaceReaders != rhs.spaceReaders {return false}
    if lhs.spaceWriters != rhs.spaceWriters {return false}
    if lhs.sharedSpaces != rhs.sharedSpaces {return false}
    if lhs.teamSeats != rhs.teamSeats {return false}
    if lhs.anyNameCount != rhs.anyNameCount {return false}
    if lhs.anyNameMinLen != rhs.anyNameMinLen {return false}
    if lhs.privateSpaces != rhs.privateSpaces {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "anytype.model"
