public enum CustomIcon: String, CaseIterable, Sendable, Codable, Identifiable {
    public init?(fromString string: String) {
        // Convert string like "musical-notes" to "musicalNotes"
        let processed = string
            .split(separator: "-")
            .enumerated()
            .map { index, part in
                if index == 0 {
                    return part.lowercased()
                }
                return part.prefix(1).uppercased() + part.dropFirst().lowercased()
            }
            .joined()
        
        self.init(rawValue: processed)
    }
    
    public var stringRepresentation: String {
        // Convert string like "musicalNotes" to "musical-notes"
        let rawValue = self.rawValue
        
        // Step 1: Find all capital letters and insert a separator before them
        var result = ""
        for (index, char) in rawValue.enumerated() {
            if char.isUppercase && index > 0 {
                result.append("-")
            }
            result.append(char.lowercased())
        }
        
        return result
    }
    
    public var id: String { rawValue }
    
    case accessibility
    case addCircle
    case airplane
    case alarm
    case albums
    case alertCircle
    case americanFootball
    case analytics
    case aperture
    case apps
    case archive
    case arrowBackCircle
    case arrowDownCircle
    case arrowForwardCircle
    case arrowRedo
    case arrowRedoCircle
    case arrowUndo
    case arrowUndoCircle
    case arrowUpCircle
    case atCircle
    case attach
    case backspace
    case bag
    case bagAdd
    case bagCheck
    case bagHandle
    case bagRemove
    case balloon
    case ban
    case bandage
    case barChart
    case barbell
    case barcode
    case baseball
    case basket
    case basketball
    case batteryCharging
    case batteryDead
    case batteryFull
    case batteryHalf
    case beaker
    case bed
    case beer
    case bicycle
    case binoculars
    case bluetooth
    case boat
    case body
    case bonfire
    case book
    case bookmark
    case bookmarks
    case bowlingBall
    case briefcase
    case browsers
    case brush
    case bug
    case build
    case bulb
    case bus
    case business
    case cafe
    case calculator
    case calendar
    case calendarClear
    case calendarNumber
    case call
    case camera
    case cameraReverse
    case car
    case carSport
    case card
    case caretBack
    case caretBackCircle
    case caretDown
    case caretDownCircle
    case caretForward
    case caretForwardCircle
    case caretUp
    case caretUpCircle
    case cart
    case cash
    case cellular
    case chatbox
    case chatboxEllipses
    case chatbubble
    case chatbubbleEllipses
    case chatbubbles
    case checkbox
    case checkmarkCircle
    case checkmarkDoneCircle
    case chevronBackCircle
    case chevronDownCircle
    case chevronForwardCircle
    case chevronUpCircle
    case clipboard
    case closeCircle
    case cloud
    case cloudCircle
    case cloudDone
    case cloudDownload
    case cloudOffline
    case cloudUpload
    case cloudy
    case cloudyNight
    case code
    case codeSlash
    case cog
    case colorFill
    case colorFilter
    case colorPalette
    case colorWand
    case compass
    case construct
    case contract
    case contrast
    case copy
    case create
    case crop
    case cube
    case cut
    case desktop
    case diamond
    case dice
    case disc
    case document
    case documentAttach
    case documentLock
    case documentText
    case documents
    case download
    case duplicate
    case ear
    case earth
    case easel
    case egg
    case ellipse
    case ellipsisHorizontalCircle
    case ellipsisVerticalCircle
    case enter
    case exit
    case expand
    case extensionPuzzle
    case eye
    case eyeOff
    case eyedrop
    case fastFood
    case female
    case fileTray
    case fileTrayFull
    case fileTrayStacked
    case film
    case filterCircle
    case fingerPrint
    case fish
    case fitness
    case flag
    case flame
    case flash
    case flashOff
    case flashlight
    case flask
    case flower
    case folder
    case folderOpen
    case football
    case footsteps
    case funnel
    case gameController
    case gift
    case gitBranch
    case gitCommit
    case gitCompare
    case gitMerge
    case gitNetwork
    case gitPullRequest
    case glasses
    case globe
    case golf
    case grid
    case hammer
    case handLeft
    case handRight
    case happy
    case hardwareChip
    case headset
    case heart
    case heartCircle
    case heartDislike
    case heartDislikeCircle
    case heartHalf
    case helpBuoy
    case helpCircle
    case home
    case hourglass
    case iceCream
    case idCard
    case image
    case images
    case infinite
    case informationCircle
    case invertMode
    case journal
    case key
    case keypad
    case language
    case laptop
    case layers
    case leaf
    case library
    case link
    case list
    case listCircle
    case locate
    case location
    case lockClosed
    case lockOpen
    case logIn
    case logOut
    case logoAlipay
    case logoAmazon
    case logoAmplify
    case logoAndroid
    case magnet
    case mail
    case mailOpen
    case mailUnread
    case male
    case maleFemale
    case man
    case map
    case medal
    case medical
    case medkit
    case megaphone
    case menu
    case mic
    case micCircle
    case micOff
    case micOffCircle
    case moon
    case move
    case musicalNote
    case musicalNotes
    case navigate
    case navigateCircle
    case newspaper
    case notifications
    case notificationsCircle
    case notificationsOff
    case notificationsOffCircle
    case nuclear
    case nutrition
    case options
    case paperPlane
    case partlySunny
    case pause
    case pauseCircle
    case paw
    case pencil
    case people
    case peopleCircle
    case person
    case personAdd
    case personCircle
    case personRemove
    case phoneLandscape
    case phonePortrait
    case pieChart
    case pin
    case pint
    case pizza
    case planet
    case play
    case playBack
    case playBackCircle
    case playCircle
    case playForward
    case playForwardCircle
    case playSkipBack
    case playSkipBackCircle
    case playSkipForward
    case playSkipForwardCircle
    case podium
    case power
    case pricetag
    case pricetags
    case print
    case prism
    case pulse
    case push
    case qrCode
    case radio
    case radioButtonOff
    case radioButtonOn
    case rainy
    case reader
    case receipt
    case recording
    case refresh
    case refreshCircle
    case reload
    case reloadCircle
    case removeCircle
    case `repeat`
    case resize
    case restaurant
    case ribbon
    case rocket
    case rose
    case sad
    case save
    case scale
    case scan
    case scanCircle
    case school
    case search
    case searchCircle
    case send
    case server
    case settings
    case shapes
    case share
    case shareSocial
    case shield
    case shieldCheckmark
    case shieldHalf
    case shirt
    case shuffle
    case skull
    case snow
    case sparkles
    case speedometer
    case square
    case star
    case starHalf
    case statsChart
    case stop
    case stopCircle
    case stopwatch
    case storefront
    case subway
    case sunny
    case swapHorizontal
    case swapVertical
    case sync
    case syncCircle
    case tabletLandscape
    case tabletPortrait
    case telescope
    case tennisball
    case terminal
    case text
    case thermometer
    case thumbsDown
    case thumbsUp
    case thunderstorm
    case ticket
    case time
    case timer
    case today
    case toggle
    case trailSign
    case train
    case transgender
    case trash
    case trashBin
    case trendingDown
    case trendingUp
    case triangle
    case trophy
    case tv
    case umbrella
    case unlink
    case videocam
    case videocamOff
    case volumeHigh
    case volumeLow
    case volumeMedium
    case volumeMute
    case volumeOff
    case walk
    case wallet
    case warning
    case watch
    case water
    case wifi
    case wine
    case woman
}
