default_platform(:ios)

platform :ios do

  lane :dev do
    deploy(
      release: false
    )
  end

  lane :release do
    deploy(
      release: true
    )
  end

  private_lane :deploy do |options| 
    match(readonly: true)
    
    build_number = increment_build_number(xcodeproj: "Anytype.xcodeproj")

    if !options[:release] 
      version = get_version_number(xcodeproj: "Anytype.xcodeproj")

      add_badge(
        shield: "#{version}-#{build_number}-blue",
        no_badge: true
      )
    end
    
    build_app(
      scheme: "Anytype", 
      configuration: options[:release] ? "Release" : "Dev-Release"
    )

    testflight
  end

  private_lane :testflight do 
    api_key = app_store_connect_api_key(
        key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
        issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
        key_content: ENV['APP_STORE_CONNECT_KEY_CONTENT'],
        duration: 1200,
        in_house: false
    )

    upload_to_testflight(
      api_key: api_key, 
      skip_waiting_for_build_processing: true
    )
  end


  # Profiles

  lane :install_dev_profiles do
    match(readonly: true)
  end

  lane :generate_dev_profiles do
    match(force_for_new_devices: true)
  end

end
