default_platform(:ios)

platform :ios do

  lane :dev do
    deploy(
      release: false
    )
  end

  lane :release do
    deploy(
      release: true
    )
  end

  private_lane :deploy do |options| 
    setup_ci
    match(readonly: true)
    
    ensure_git_status_clean

    build_number = increment_build_number(xcodeproj: "Anytype.xcodeproj")
    version = get_version_number(xcodeproj: "Anytype.xcodeproj")

    commit_version_bump(
      message: "Bump version #{version}(#{build_number})",
      xcodeproj: "Anytype.xcodeproj"
    )

    prefix = options[:release] ? "release" : "dev"
    add_git_tag(
      tag: "#{prefix}/#{version}/#{build_number}",
      force: true
    )

    if !options[:release] 
      add_badge(
        shield: "#{version}-#{build_number}-blue",
        no_badge: true
      )
    end
    
    build_app(
      scheme: "Anytype", 
      configuration: options[:release] ? "Release" : "Dev-Release",
      include_symbols: true,
      use_system_scm: true
    )

    upload_build_to_testflight

    # Reset icon changes
    reset_git_repo(skip_clean: true)

    push_to_git_remote

    upload_dsyms_to_crashlytics(release: options[:release])
  end

  private_lane :upload_build_to_testflight do 
    api_key = app_store_connect_api_key(
        key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
        issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
        key_content: ENV['APP_STORE_CONNECT_KEY_CONTENT'],
        duration: 1200,
        in_house: false
    )

    upload_to_testflight(
      api_key: api_key, 
      skip_waiting_for_build_processing: true
    )
  end

  private_lane :upload_dsyms_to_crashlytics do |options| 
    release_plist = "./Anytype/Resources/Plists/GoogleService-Info.plist"
    dev_plist = "./Anytype/Resources/Plists/GoogleService-Info-Dev.plist"

    upload_symbols_to_crashlytics(
      gsp_path: options[:release] ? release_plist : dev_plist
    )
  end

  # Test

  lane :test_build do
    setup_ci
    match(readonly: true)

    build_app(
      derived_data_path: "~/DerivedData/Anytype/",
      scheme: "Anytype", 
      configuration: "Dev-Release",
      include_symbols: true,
      use_system_scm: true
    )

  end

  lane :bump_dev_version do
    ensure_git_status_clean

    build_number = increment_build_number(xcodeproj: "Anytype.xcodeproj")
    version = get_version_number(xcodeproj: "Anytype.xcodeproj")

    commit_version_bump(
      message: "Bump version #{version}(#{build_number})",
      xcodeproj: "Anytype.xcodeproj"
    )

    add_git_tag(tag: "dev/#{version}/#{build_number}")
  end

  # Profiles

  lane :install_dev_profiles do
    match(readonly: true)
  end

  lane :install_appstore_profiles do
    match(readonly: true)
  end

  lane :generate_dev_profiles do
    match(force_for_new_devices: true)
  end

end
