name: Prepare deps
runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - shell: bash
      run: bundle install
    - uses: tecolicom/actions-use-homebrew-tools@v1
      with:
        tools: imagemagick libgit2
