require_relative 'workers/asset_url_worker'
require_relative 'workers/available_versions_worker'
require_relative 'workers/download_file_worker'
require_relative 'workers/remote_info_worker'
require_relative 'workers/remote_version_worker'
require_relative 'workers/cleanup_worker'