require_relative 'workers/asset_url_worker'
require_relative 'workers/available_versions_worker'
require_relative 'workers/copy_artifacts_worker'
require_relative 'workers/copy_protobuf_worker'
require_relative 'workers/download_file_worker'
require_relative 'workers/library_version_worker'
require_relative 'workers/remote_info_worker'
require_relative 'workers/remote_version_worker'
require_relative 'workers/compare_versions_worker'
require_relative 'workers/cleanup_worker'

require_relative 'workers/traveler_worker'