name: Auto-merge-actions

on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  dependencies:
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions'

    steps:
    
      - uses: hmarr/auto-approve-action@v4