name: Branch build

on:
  pull_request_target:
    types: [opened,closed,synchronize]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tf_comment:
        description: 'TestFlight Comment'
        default: ''

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  main:
    runs-on: ${{ vars.RUNNER }}
    if: github.event.pull_request.head.repo.fork || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
           fetch-depth: 0

      - name: Install SSH key for access to repository
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_ACCESS_KEY }}

      - name: Update git config
        uses: ./.github/actions/update-git-config

      - name: Prepare deps
        uses: ./.github/actions/prepare-deps

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '16.1'

      - name: Download Middleware
        run: make setup-middle-ci
        env:
          MIDDLEWARE_TOKEN: ${{ secrets.MIDDLEWARE_TOKEN }}

      - name: Build and upload to Testflight
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          bundle exec fastlane branch_build tf_comment:"${{ github.event.inputs.tf_comment }}"
        env:
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.SSH_KEY_FASTLANE_MATCH }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          LINEAR_TOKEN: ${{ secrets.LINEAR_TOKEN }}
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          AI_ENDPOINT: ${{ secrets.AI_ENDPOINT }}
          AI_MODEL: ${{ secrets.AI_MODEL }}
          ANY_APP_MEMBERSHIP_TIER_SECRET: ${{ secrets.ANY_APP_MEMBERSHIP_TIER_SECRET }}
          JOIN_STREAM_URL: ${{ secrets.JOIN_STREAM_URL }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 900
          FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 4

      - name: Summary
        run: echo "${{ env.FASTLANE_SUMMARY }}" >> $GITHUB_STEP_SUMMARY
