name: Check generated files

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Check
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Restore cache for local build folder
        uses: actions/cache/restore@v4
        with:
          path: build
          key: build-local-tools-${{ github.sha }}
          restore-keys: |
            build-local-tools-

      - name: Setup tools
        run: make setup-env
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Middleware and Generate Files
        run: make setup-middle
        env:
          MIDDLEWARE_TOKEN: ${{ secrets.MIDDLEWARE_TOKEN }}

      - name: Run generate
        run: make generate

      - name: Check for modified files
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "::error::Generated files are not up to date. Please run 'make generate' and commit the changes."
            git status
            exit 1
          fi
